[package]
name = "monumentum_query"
readme = "readme.md"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
description = "SQL-like query parser for Monumentum."

[dependencies]
monumentum_db = {path = "../monumentum_db", version = "0.1.0" }

[dev-dependencies]
proptest = "1.4"
pretty_assertions = "1.4"