[package]
name = "monumentum_functions"
version = "0.1.0"
description = "Preset spreadsheet functions for Monumentum"
readme = "readme.md"
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
monumentum_db = { path = "../monumentum_db", version = "0.1.0" }
monumentum_query = { path = "../monumentum_query", version = "0.1.0" }

[lints]
workspace = true
