[package]
name = "monumentum_db"
readme = "readme.md"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
description = "Core database engine for Monumentum, built with Rust std only."

[dependencies]


[dev-dependencies]
tempfile = "3"
proptest = "1"
pretty_assertions = "1"